"""initial schema

Revision ID: 122fa6101515
Revises: 
Create Date: 2026-04-20 19:04:18.275915

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122fa6101515'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_external_id'), 'job', ['external_id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_emoji', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rag_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=False)
    op.create_table('baseresume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('docx_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseresume_profile_id'), 'baseresume', ['profile_id'], unique=False)
    op.create_table('panelsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviews_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panelsession_profile_id'), 'panelsession', ['profile_id'], unique=False)
    op.create_table('pipelinecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('DISCOVERED', 'APPLIED', 'SCREENER', 'INTERVIEW', 'OFFER', 'CLOSED', name='pipelinestage'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelinecard_profile_id'), 'pipelinecard', ['profile_id'], unique=False)
    op.create_table('savedjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savedjob_profile_id'), 'savedjob', ['profile_id'], unique=False)
    op.create_table('coverletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_card_id', sa.Integer(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_card_id'], ['pipelinecard.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverletter_profile_id'), 'coverletter', ['profile_id'], unique=False)
    op.create_table('resumeversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_resume_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_card_id', sa.Integer(), nullable=True),
    sa.Column('docx_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('jd_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_resume_id'], ['baseresume.id'], ),
    sa.ForeignKeyConstraint(['pipeline_card_id'], ['pipelinecard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumeversion_base_resume_id'), 'resumeversion', ['base_resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumeversion_base_resume_id'), table_name='resumeversion')
    op.drop_table('resumeversion')
    op.drop_index(op.f('ix_coverletter_profile_id'), table_name='coverletter')
    op.drop_table('coverletter')
    op.drop_index(op.f('ix_savedjob_profile_id'), table_name='savedjob')
    op.drop_table('savedjob')
    op.drop_index(op.f('ix_pipelinecard_profile_id'), table_name='pipelinecard')
    op.drop_table('pipelinecard')
    op.drop_index(op.f('ix_panelsession_profile_id'), table_name='panelsession')
    op.drop_table('panelsession')
    op.drop_index(op.f('ix_baseresume_profile_id'), table_name='baseresume')
    op.drop_table('baseresume')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_job_external_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
